### ISSUE TITLE
[UAT site] Error in server - when submitting contact card

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/MSF-REACH-COLLABORATION#105]
![image](https://user-images.githubusercontent.com/25951555/65334271-62d86d00-dbc2-11e9-91e1-4ba1972247bb.png)

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/67757367-f744b380-fa3b-11e9-8049-5bd3a991cb3b.png)

Still the case on 29.10.2019 ; when adding individual contact card.

**Comment by hohangleung** [comment]
Please check again.
If the issue still exist, please capture the screenshot that shows your inputs and selected options.

**Comment by LucieGueuning** [comment]
@hohangleung I can't reproduce this bug anymore. Might be solved. Thanks
