### ISSUE TITLE
[UAT site] Menu selection missing on map - missing map layers

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/MSF-REACH-COLLABORATION#127]

**Comment by LucieGueuning** [comment]
Still missing on **every** map of the UAT site

![image](https://user-images.githubusercontent.com/25951555/72145329-f799ed00-33a2-11ea-851c-10c79e927dd4.png)

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/72148189-df2cd100-33a8-11ea-9a43-d6f6ded7b1ae.png)

**Comment by hohangleung** [comment]
The first two style (thematic / terrain) on UX site are custom style created by previous vendor and cannot be used directly. 
May I know if we have access of that specific MapBox account?

**Comment by LucieGueuning** [comment]
Yes, you should have access to the specific MapBox account. Please check with Chi Wai. 

@pmeinhardt would you mind sharing with us the credentials for that? Thanks!

**Comment by pmeinhardt** [comment]
> @pmeinhardt would you mind sharing with us the credentials for that? Thanks!

Hi @LucieGueuning 👋🙂 I don't have access to any MapBox account as far as I know. I guess you meant to "@"-mention someone else? Cheers

**Comment by chiwaileung** [comment]
@LucieGueuning Please refer to #182, close it.
