### ISSUE TITLE
[UAT site] External Report Card - first slide wrong - make sure the sentence is right: I agree that relevant MSF staff can contact me to discuss emergency-related media, communications and fundraising issues

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/MSF-REACH-COLLABORATION#133]
![image](https://user-images.githubusercontent.com/25951555/72153685-4e112680-33b7-11ea-9caf-9a5507d45c2e.png)

cf issue #116

**Comment by hohangleung** [comment]
Follow the screenshot provided in #116 
Should we add / replace the text? Please advise

**Comment by LucieGueuning** [comment]
The sentence should be added - please follow the sketches 

I agree that relevant MSF staff can contact me to discuss emergency-related media, communications and fundraising issues

![image](https://user-images.githubusercontent.com/25951555/72243522-d6c8d600-35f4-11ea-96a9-a136b95765fa.png)

**Comment by hohangleung** [comment]
Updated, please check
